name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
    - name: Change gradlew mode
      run:  chmod +x gradlew
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build  
